### ISSUE TITLE
Does not work on Nexus 5x or S6

### ISSUE THREAD

**Issue by theodesp** [cakuki/cordova-plugin-exit#1]
Just tested in on a Nexus 5x and S6 and it does not work. I work fine on iPhone6,7,8

**Comment by meishier** [comment]
same here

**Comment by cakuki** [comment]
@theodesp & @meishier could you please test with the new version (1.0.3) too? I think I had messed up complete Android platform before. It took me too long to get back I know but if any chance if you are still into it, I'd love to get your feedback on this.

**Comment by cakuki** [comment]
I am closing the issue as I assume it is fixed. Please let me know if it's not the case.
