### ISSUE TITLE
Class not found on Android

### ISSUE THREAD

**Issue by italrap** [cakuki/cordova-plugin-exit#2]
Plugin doesn't work in android. Logcat displays the error:
.... java.lang.ClassNotFoundException: Didn't find class "im.ckk.cordova.exit" on path ....

Solved replacing in file plugin.xml following lines:

`
<feature name="Exit">
        <param name="android-package" value="im.ckk.cordova.exit" />
</feature>
`
with 
`<feature name="Exit">
        <param name="android-package" value="im.ckk.cordova.exit.Exit" />
</feature>`

**Comment by cakuki** [comment]
This should have been fixed with #3, I will close this issue after releasing the version. Thanks for reporting!

**Comment by cakuki** [comment]
Seems like it's been fixed with #3.
